# Generated by Django 5.0.6 on 2024-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='where',
            field=models.TextField(default='未知'),
            preserve_default=False,
        ),
    ]
